### PR TITLE
Background Music

### PR DESCRIPTION
**Pull request by Wans-G**
Check this link: https://glacial-earth-53191-9338a44d997f.herokuapp.com/ to get full experience
userEmail: a@a.a 
userPassword: password

*Localhost version acts a little differently compared to deployed version, since the asset pipeline in development env is not pre-compiled(as default), so the music loading time is sometimes very slow.

## Major Updates (PR #67)

1. First-Time User Discount Display
- If a user is visiting the website for the first time, the shop page now displays a special discount.
- **Note:** The in-store page layout will be updated once all store items are finalized.

2. Forgot-Password Navigation
- Added a link from the forgot-password page back to the login page for easier navigation.

3. Cucumber Test Adjustments
- Updated tests so the first-time login page no longer conflicts with legacy test scenarios.

## Background Music Updates

4. New Music Assets
- Added two AI-generated songs to the asset pipeline.

5. Page Assignments
- Assigned these songs to specific pages for an enhanced user experience.

6. Automatic Playback
- Music now auto-plays when navigating between pages.

7. Future Music Additions
- Introducing a simplified approach: add just one line of code to integrate new songs into any page.

## Testing Coverage
- Current test coverage: **93%**.

This update enhances the first-time user experience, improves navigation flows, aligns tests with the updated login logic, and introduces dynamic audio functionality.

### CODE REVIEW

**Comment by bjohnson66** [comment]
Music on Landing page would be fine and login pages. 
I wouldn't have it on the game page. 
Perhaps calmer music or no music on shop page.
Can we do some instrumental tavern music on friends page

**Comment by bjohnson66** [comment]
Can we use same music as login page on settings page? or no music?

**Review by zhasa18 — APPROVED** [review]
I think this is really good! I think the music fits the game well! I also, think that Bradley's review comments aren't a bad idea to pursue but if you don't its fine either way.

**Comment by Wans-G** [comment]
Changing and removing music is very straightforward—it only takes one line of code. However, I'll wait to see if anyone has time to generate or find suitable music. I suggest don't spending time on this until we finish the main game. It can be time-consuming, especially if you're unlucky and keep generating unrelated songs. I was lucky to get two good songs in the first try. I can have an update on the next patch to disable music on some pages

**Pull request merged**
