### PR TITLE
22 profile page forgot password

### PR DESCRIPTION
**Pull request by bjohnson66**
Bug Fixes and Imrpovements:
- Fixed 0Auth redirect URL to be https
- Fixed forgot password and 0auth redirect urls to be dynamically based on ENV variable
- Fixed style of forgot password and reset password pages
- Made emails actually send to clients
- Pwd reset tokens invalidate after succesful reset

### CODE REVIEW

**Comment by bjohnson66** [comment]
https://shards-of-the-grid-i2dev-615e05ea270d.herokuapp.com/login

Test it here

**Comment by 12callison** [comment]
No conflicts on my branch

**Comment by bjohnson66** [comment]
0Auth is  not working but was broken before my changes
crated story for Jerry to fix it and add the tests (which werent there in the first place)

**Review by zhasa18 — APPROVED** [review]
No issues when I ran it locally : )

**Pull request merged**
